version: '3'
services:
  db:
    image: postgres
  app:
    build: .
    command: /emr-barbershop/run.sh
    volumes:
      - .:/emr-barbershop
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env