# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a57efa719afa692d8c6b9690beb33f5137607882d8b5fd3071101ab063a4756de1bcc0ec99b052889fd60355da8753eeb8a8a98bf38e11584579ba2d3b00a2a

test:
  secret_key_base: 08bc37fcf74b7c7ebe75d9c574ed47d174616d9450fc49dc888190839ce0cb31932d67551e8e4cda7e374cfbead0194529d0ad04ce1f25f2b5bc6ee746e69d22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
